org: dominopianino
app: skeleton
service: skeleton
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S #
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    BookTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Book
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S 
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
